spring:
  application:
    name: attendance-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: attendance-service
    description: HR SaaS - Attendance Management Service
    version: 1.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/