server:
  port: 8222

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hr-saas
  cloud:
    gateway:
      mvc:
        routes:
          - id: employee-service
            uri: lb://employee-service
            predicates:
              - Path=/api/employees/**

          - id: attendance-service
            uri: lb://attendance-service
            predicates:
              - Path=/api/attendance/**

          - id: leave-service
            uri: lb://leave-service
            predicates:
              - Path=/api/leaves/**

          - id: notification-service
            uri: lb://notification-service
            predicates:
              - Path=/api/notify/**

          - id: project-service
            uri: lb://project-service
            predicates:
              - Path=/api/projects/**, /api/tasks/**, /api/timelogs/**, /api/companies/**, /api/dashboard/**

          - id: gamification-service
            uri: lb://gamification-service
            predicates:
              - Path=/api/gamification/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/