spring.application.name=employee-service
server.port=8081

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:employeedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (browser me DB dekh sakte ho)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always
management.info.env.enabled=true

# App info (info endpoint pe dikhega)
info.app.name=employee-service
info.app.description=HR SaaS - Employee Management Service
info.app.version=1.0.0