// Report export helpers — report-agnostic.
// headers: string[] (column labels), rows: string[][] (already-stringified cells).
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

// CSV field ko safe banao: comma/quote/newline ho to quotes me wrap + quotes double
function csvEscape(v) {
  const s = v == null ? '' : String(v)
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

export function downloadCSV(filename, headers, rows) {
  const lines = [
    headers.map(csvEscape).join(','),
    ...rows.map(r => r.map(csvEscape).join(',')),
  ]
  // ﻿ (BOM) → Excel UTF-8 sahi padhe (accents/₹ na tootein)
  const blob = new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' })
  triggerDownload(blob, filename)
}

// Logo asset (Vite URL) → { dataUrl, w, h } for jsPDF addImage.
// Downscale to maxH so embedded PNG chhota rahe (warna PDF megabytes me chala jata hai).
export function loadImageAsset(url, maxH = 160) {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => {
      const scale = Math.min(1, maxH / img.naturalHeight)
      const w = Math.round(img.naturalWidth * scale)
      const h = Math.round(img.naturalHeight * scale)
      const cv = document.createElement('canvas')
      cv.width = w
      cv.height = h
      cv.getContext('2d').drawImage(img, 0, 0, w, h)
      resolve({ dataUrl: cv.toDataURL('image/png'), w, h })
    }
    img.onerror = reject
    img.src = url
  })
}

// brand = { dataUrl, w, h } (logo) | null. CSV stays unbranded — branding sirf PDF me.
export function downloadPDF(filename, title, headers, rows, brand) {
  // 6+ columns → landscape (warna table kat-ti hai)
  const doc = new jsPDF({ orientation: headers.length > 6 ? 'landscape' : 'portrait' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const M = 14
  let y = 13

  // ── Letterhead: logo mark + wordmark + tagline ──
  let textX = M
  if (brand?.dataUrl) {
    const logoH = 13
    const logoW = logoH * (brand.w / brand.h)
    doc.addImage(brand.dataUrl, 'PNG', M, y, logoW, logoH)
    textX = M + logoW + 5
  }
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(22, 101, 52)                 // Taurus green
  doc.text('Taurus', textX, y + 8)
  const w1 = doc.getTextWidth('Taurus ')
  doc.setTextColor(184, 134, 11)                // Go gold (dark enough for white bg)
  doc.text('Go', textX + w1, y + 8)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text('Work Smart. Go Further.', textX, y + 13)

  y += 18
  doc.setDrawColor(22, 163, 74)                 // green rule
  doc.setLineWidth(0.6)
  doc.line(M, y, pageW - M, y)
  y += 8

  // ── Report title + meta ──
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(20, 37, 26)
  doc.text(title, M, y)
  y += 6
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(120, 120, 120)
  doc.text(`Generated ${new Date().toLocaleString('en-IN')}  ·  ${rows.length} rows`, M, y)

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: y + 4,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [22, 163, 74], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [244, 248, 245] },
    margin: { top: 14, bottom: 16 },
    didDrawPage: () => {
      // Footer har page pe
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('Generated by Taurus Go', M, pageH - 8)
      doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber}`, pageW - M, pageH - 8, { align: 'right' })
    },
  })

  doc.save(filename)
}
