// Report export helpers — report-agnostic.
// headers: string[] (column labels), rows: string[][] (already-stringified cells).
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

// CSV field ko safe banao: comma/quote/newline ho to quotes me wrap + quotes double
function csvEscape(v) {
  const s = v == null ? '' : String(v)
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

export function downloadCSV(filename, headers, rows) {
  const lines = [
    headers.map(csvEscape).join(','),
    ...rows.map(r => r.map(csvEscape).join(',')),
  ]
  // ﻿ (BOM) → Excel UTF-8 sahi padhe (accents/₹ na tootein)
  const blob = new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' })
  triggerDownload(blob, filename)
}

// Logo asset (Vite URL) → { dataUrl, w, h } for jsPDF addImage.
// Downscale to maxH so embedded PNG chhota rahe (warna PDF megabytes me chala jata hai).
export function loadImageAsset(url, maxH = 160) {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => {
      const scale = Math.min(1, maxH / img.naturalHeight)
      const w = Math.round(img.naturalWidth * scale)
      const h = Math.round(img.naturalHeight * scale)
      const cv = document.createElement('canvas')
      cv.width = w
      cv.height = h
      cv.getContext('2d').drawImage(img, 0, 0, w, h)
      resolve({ dataUrl: cv.toDataURL('image/png'), w, h })
    }
    img.onerror = reject
    img.src = url
  })
}

// Shared Taurus Go letterhead (logo mark + wordmark + tagline + green rule).
// startY se shuru; rule ke neeche ki y laut-ta hai (content wahin se aage).
function drawLetterhead(doc, brand, M, pageW, startY = 13) {
  let y = startY
  let textX = M
  if (brand?.dataUrl) {
    const logoH = 13
    const logoW = logoH * (brand.w / brand.h)
    doc.addImage(brand.dataUrl, 'PNG', M, y, logoW, logoH)
    textX = M + logoW + 5
  }
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(22, 101, 52)                 // Taurus green
  doc.text('Taurus', textX, y + 8)
  const w1 = doc.getTextWidth('Taurus ')
  doc.setTextColor(184, 134, 11)                // Go gold (dark enough for white bg)
  doc.text('Go', textX + w1, y + 8)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text('Work Smart. Go Further.', textX, y + 13)

  y += 18
  doc.setDrawColor(22, 163, 74)                 // green rule
  doc.setLineWidth(0.6)
  doc.line(M, y, pageW - M, y)
  return y + 8
}

// brand = { dataUrl, w, h } (logo) | null. CSV stays unbranded — branding sirf PDF me.
export function downloadPDF(filename, title, headers, rows, brand) {
  // 6+ columns → landscape (warna table kat-ti hai)
  const doc = new jsPDF({ orientation: headers.length > 6 ? 'landscape' : 'portrait' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const M = 14
  let y = drawLetterhead(doc, brand, M, pageW)

  // ── Report title + meta ──
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(20, 37, 26)
  doc.text(title, M, y)
  y += 6
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(120, 120, 120)
  doc.text(`Generated ${new Date().toLocaleString('en-IN')}  ·  ${rows.length} rows`, M, y)

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: y + 4,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [22, 163, 74], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [244, 248, 245] },
    margin: { top: 14, bottom: 16 },
    didDrawPage: () => {
      // Footer har page pe
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('Generated by Taurus Go', M, pageH - 8)
      doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber}`, pageW - M, pageH - 8, { align: 'right' })
    },
  })

  doc.save(filename)
}

const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December']
const inr = n => 'Rs. ' + Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })

// Ek payslip ka branded PDF (letterhead + earnings/deductions + net pay highlight).
// p = payslip object (backend jaisa), brand = { dataUrl, w, h } | null.
export function downloadPayslipPDF(p, brand) {
  const doc = new jsPDF({ orientation: 'portrait' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const M = 14
  let y = drawLetterhead(doc, brand, M, pageW)

  // Title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(20, 37, 26)
  doc.text('Payslip', M, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(90, 107, 96)
  doc.text(`${MONTH_NAMES[p.month - 1]} ${p.year}`, pageW - M, y, { align: 'right' })
  y += 7

  // Employee + attendance summary
  doc.setFontSize(10)
  doc.setTextColor(60, 60, 60)
  doc.text(`Employee: ${p.employeeName || '#' + p.employeeId}`, M, y)
  y += 5
  doc.setTextColor(120, 120, 120)
  doc.setFontSize(9)
  doc.text(
    `Absent: ${p.absentDays}   |   Approved leave: ${p.approvedLeaveDays} (paid ${p.paidLeaveDays}, unpaid ${p.unpaidLeaveDays})   |   LOP days: ${p.lopDays}`,
    M, y)
  y += 4

  // Earnings table
  autoTable(doc, {
    startY: y + 2,
    head: [['Earnings', 'Amount']],
    body: [
      ['Basic', inr(p.basic)],
      ['HRA', inr(p.hra)],
      ['Special Allowance', inr(p.specialAllowance)],
      [{ content: 'Gross Pay', styles: { fontStyle: 'bold' } }, { content: inr(p.grossPay), styles: { fontStyle: 'bold' } }],
    ],
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: [22, 163, 74], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: M, right: M },
  })

  // Deductions table
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 4,
    head: [['Deductions', 'Amount']],
    body: [
      ['Provident Fund (PF)', inr(p.pf)],
      ['Professional Tax', inr(p.professionalTax)],
      [`Loss of Pay (${p.lopDays} day${p.lopDays === 1 ? '' : 's'})`, inr(p.lopAmount)],
      [{ content: 'Total Deductions', styles: { fontStyle: 'bold' } }, { content: inr(p.totalDeductions), styles: { fontStyle: 'bold' } }],
    ],
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: [100, 116, 139], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: M, right: M },
  })

  // Net Pay highlight box
  const boxY = doc.lastAutoTable.finalY + 8
  doc.setFillColor(234, 247, 238)              // light green
  doc.setDrawColor(22, 163, 74)
  doc.setLineWidth(0.4)
  doc.roundedRect(M, boxY, pageW - 2 * M, 16, 2, 2, 'FD')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(20, 83, 45)
  doc.text('Net Pay (Take-home)', M + 5, boxY + 10)
  doc.setFontSize(14)
  doc.setTextColor(22, 101, 52)
  doc.text(inr(p.netPay), pageW - M - 5, boxY + 10, { align: 'right' })

  // Footer
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('This is a system-generated payslip.  Generated by Taurus Go.', M, pageH - 8)

  doc.save(`payslip-${p.year}-${String(p.month).padStart(2, '0')}.pdf`)
}
