spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/attendancedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  welcome-message: "HR SaaS Attendance Service - Version 1"