spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/attendancedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1230
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true